# Generated by Django 5.2.1 on 2025-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='major',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(default=100, max_length=3),
            preserve_default=False,
        ),
    ]
